# Generated by Django 4.0.6 on 2022-07-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ts_system', '0001_migration_name'),
    ]

    operations = [

    ]
