# Generated by Django 4.0.4 on 2022-08-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_system', '0005_alter_ts_data_is_shipped_alter_ts_data_utid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ts_data',
            name='Is_SHIPPED',
        ),
        migrations.AddField(
            model_name='ts_data',
            name='IS_SHIPPED',
            field=models.BooleanField(default=False),
        ),
    ]
