# Generated by Django 4.0.4 on 2022-08-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_system', '0006_remove_ts_data_is_shipped_ts_data_is_shipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ts_data',
            name='AiD_SSiD',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='BBSE',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='Comment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='Comments2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='Compensator',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='Customer',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='Handler',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='K_MAT',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='MSWAVECAL',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='NLR_Ceramic_Chuck',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='OPTION_LDSR',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='Open_Date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='Others',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='SO_FID',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='Ship_Date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='Tester_Type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='Tool',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='UTID',
            field=models.CharField(max_length=250, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='UVR_eUVR',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='WLR_FD',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='WO1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='WO10',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='WO2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='WO3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='WO4',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='WO5',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='WO6',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='WO7',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='WO8',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='WO9',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='tool_status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
