# Generated by Django 4.0.4 on 2022-08-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_system', '0007_alter_ts_data_aid_ssid_alter_ts_data_bbse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ts_data',
            name='Tool_owner',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ts_data',
            name='WO11',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ts_data',
            name='WO12',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ts_data',
            name='WO13',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
