# Generated by Django 4.0.4 on 2022-08-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_system', '0008_ts_data_tool_owner_ts_data_wo11_ts_data_wo12_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ts_data',
            name='SO_FID',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ts_data',
            name='UTID',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
