# Generated by Django 4.0.4 on 2022-08-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_system', '0012_alter_ts_data_so_fid_alter_ts_data_utid'),
    ]

    operations = [
        migrations.CreateModel(
            name='sap_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PLANT', models.CharField(blank=True, max_length=250, null=True)),
                ('MATERIAL', models.CharField(blank=True, max_length=250, null=True)),
                ('MAKTX', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
