# Generated by Django 4.0.4 on 2022-08-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_system', '0013_sap_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_data',
            fields=[
                ('UTID', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
                ('Argo_ID', models.CharField(blank=True, max_length=250, null=True)),
                ('flex01', models.CharField(blank=True, max_length=250, null=True)),
                ('sales_order', models.CharField(blank=True, max_length=250, null=True)),
                ('fab_name', models.CharField(blank=True, max_length=250, null=True)),
                ('commit_date', models.CharField(blank=True, max_length=250, null=True)),
                ('BuildQtr', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
