# Generated by Django 4.0.4 on 2022-08-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_system', '0014_daily_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='argo_data',
            fields=[
                ('Argo_ID', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
                ('UTID', models.CharField(blank=True, max_length=250, null=True)),
                ('flex01', models.CharField(blank=True, max_length=250, null=True)),
                ('sales_order', models.CharField(blank=True, max_length=250, null=True)),
                ('fab_name', models.CharField(blank=True, max_length=250, null=True)),
                ('commit_date', models.CharField(blank=True, max_length=250, null=True)),
                ('BuildQtr', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='sap_data',
        ),
        migrations.AlterField(
            model_name='daily_data',
            name='Argo_ID',
            field=models.CharField(max_length=250, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='daily_data',
            name='UTID',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
