# Generated by Django 4.0.4 on 2022-08-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_system', '0015_argo_data_delete_sap_data_alter_daily_data_argo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ts_data',
            name='Argo_ID',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ts_data',
            name='tool_family',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='argo_data',
            name='commit_date',
            field=models.DateField(null=True),
        ),
    ]
