# Generated by Django 4.0.4 on 2022-08-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_system', '0016_ts_data_argo_id_ts_data_tool_family_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ts_data',
            name='WO11',
        ),
        migrations.RemoveField(
            model_name='ts_data',
            name='WO12',
        ),
        migrations.RemoveField(
            model_name='ts_data',
            name='WO13',
        ),
        migrations.AddField(
            model_name='ts_data',
            name='BuildQtr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='argo_data',
            name='commit_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
