# Generated by Django 4.0.4 on 2022-09-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_system', '0017_remove_ts_data_wo11_remove_ts_data_wo12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ts_data',
            name='Configuration',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
