# Generated by Django 4.0.4 on 2022-09-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_system', '0018_ts_data_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ts_data',
            name='Tool_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
