# Generated by Django 4.0.4 on 2022-09-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_system', '0019_ts_data_tool_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='argo_data',
            name='Tool_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
