# Generated by Django 4.0.4 on 2022-09-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_system', '0022_remove_argo_data_tool_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='argo_data',
            name='Tool_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ts_data',
            name='Tool_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
