# Generated by Django 4.0.4 on 2022-09-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_system', '0023_argo_data_tool_start_date_ts_data_tool_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argo_data',
            name='Argo_ID',
            field=models.CharField(default=None, max_length=250, primary_key=True, serialize=False),
        ),
    ]
