# Generated by Django 4.0.4 on 2022-09-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_system', '0024_alter_argo_data_argo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='argo_data',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='argo_data',
            name='Argo_ID',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
