# Generated by Django 4.0.4 on 2022-09-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts_system', '0028_argo_data_id_alter_argo_data_argo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='argo_data',
            name='Argo_ID',
        ),
    ]
