# Generated by Django 4.0.4 on 2022-09-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_system', '0029_remove_argo_data_argo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='argo_data',
            name='Argo_ID',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
