# Generated by Django 4.0.4 on 2022-09-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_system', '0030_argo_data_argo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ts_data',
            name='Ship_Date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
