# Generated by Django 4.0.4 on 2022-10-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_system', '0033_alter_ts_data_open_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('Argo_ID', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
                ('PNs', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='previous_argo_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Argo_ID', models.CharField(default=None, max_length=250)),
                ('UTID', models.CharField(blank=True, max_length=250, null=True)),
                ('flex01', models.CharField(blank=True, max_length=250, null=True)),
                ('sales_order', models.CharField(blank=True, max_length=250, null=True)),
                ('fab_name', models.CharField(blank=True, max_length=250, null=True)),
                ('commit_date', models.CharField(blank=True, max_length=250, null=True)),
                ('BuildQtr', models.CharField(blank=True, max_length=250, null=True)),
                ('Tool_start_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='wos',
            fields=[
                ('Order', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
                ('Material', models.CharField(blank=True, max_length=250, null=True)),
                ('Material_Description', models.CharField(blank=True, max_length=250, null=True)),
                ('Plant', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
